// Code generated by go-bindata.
// sources:
// ddl.go
// ddl_gen.go
// postgres/1_init.sql
// DO NOT EDIT!

package ddl

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _ddlGo = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x14\xc9\xc1\x09\x80\x30\x0c\x05\xd0\x7b\xa7\xc8\x02\x4d\xee\x2e\x23\xd1\x7c\x3e\x52\x49\x8a\x74\x7f\xa4\xa7\x77\x78\x66\xac\x83\x48\x7c\xbe\x20\xac\x7e\x3d\x19\xbe\x5c\xfa\x1c\x94\x88\x57\x7a\x6d\x4e\x22\x95\x25\x6a\xaa\xda\xa6\xdf\xc3\x89\x1d\xed\x0f\x00\x00\xff\xff\xef\x5c\x6f\xa3\x42\x00\x00\x00")

func ddlGoBytes() ([]byte, error) {
	return bindataRead(
		_ddlGo,
		"ddl.go",
	)
}

func ddlGo() (*asset, error) {
	bytes, err := ddlGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "ddl.go", size: 66, mode: os.FileMode(420), modTime: time.Unix(1496166086, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _ddl_genGo = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func ddl_genGoBytes() ([]byte, error) {
	return bindataRead(
		_ddl_genGo,
		"ddl_gen.go",
	)
}

func ddl_genGo() (*asset, error) {
	bytes, err := ddl_genGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "ddl_gen.go", size: 0, mode: os.FileMode(420), modTime: time.Unix(1496169186, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _postgres1_initSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x7c\x90\x31\x4f\xc3\x30\x10\x85\x77\xff\x8a\x37\x26\x12\x03\x7b\x26\xb7\x3e\x2a\x0b\x73\x46\xee\x59\x6a\x26\xab\xc2\x19\x2c\x22\xa8\xea\x20\xd1\x7f\xcf\x50\xa7\x82\x81\xbe\xf1\xee\x7b\xc3\xf7\xb6\x81\xb4\x10\x44\x6f\x1c\xe1\xeb\xa3\x2c\x15\x9d\x02\x4a\xc6\xaf\xc4\x68\x0d\xfe\x84\xbd\x80\xa3\x73\x0f\x0a\x78\x9b\x8f\xb5\xa6\xb5\x71\x9f\x5d\xca\x32\x4f\xb7\x8f\xd0\x41\xfe\x67\x73\xa9\xa7\xf9\x78\x49\x9f\xe7\x3c\x9d\x61\x59\x68\x47\x01\x86\x9e\x74\x74\x82\xc7\x1b\xab\xfa\x41\x69\x27\x14\x9a\x85\x67\x37\x5e\x55\x14\xa0\x8d\xc1\xd6\xf3\x5e\x82\xb6\x2c\xd7\x73\x3a\xbd\x4f\x17\xbc\x06\xfb\xa2\xc3\x88\x67\x1a\xd1\x95\xdc\x0f\xaa\x6d\x61\xd9\xd0\xa1\x91\xab\x5b\x2a\xf9\x5b\x01\x9e\xdb\x46\x71\x6f\x79\x87\x8d\x04\x22\x74\x2b\xd4\x0f\x3f\x01\x00\x00\xff\xff\x27\x79\xb6\xfa\x4e\x01\x00\x00")

func postgres1_initSqlBytes() ([]byte, error) {
	return bindataRead(
		_postgres1_initSql,
		"postgres/1_init.sql",
	)
}

func postgres1_initSql() (*asset, error) {
	bytes, err := postgres1_initSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "postgres/1_init.sql", size: 334, mode: os.FileMode(420), modTime: time.Unix(1496169184, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"ddl.go": ddlGo,
	"ddl_gen.go": ddl_genGo,
	"postgres/1_init.sql": postgres1_initSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"ddl.go": &bintree{ddlGo, map[string]*bintree{}},
	"ddl_gen.go": &bintree{ddl_genGo, map[string]*bintree{}},
	"postgres": &bintree{nil, map[string]*bintree{
		"1_init.sql": &bintree{postgres1_initSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

